### ISSUE TITLE
IMESupport not run win10

### ISSUE THREAD

**Issue by tennc** [chikatoike/IMESupport#19]
win10 64 + sublime text3  
IMESupport not run
can you update ??

**Comment by kngxscn** [comment]
I have this problem, too...

**Comment by junhaoim** [comment]
Same here. Can you solve this please?

**Comment by kngxscn** [comment]
Some days ago I change my input method from win10 default IME to Google pinyin input method, and IMESupport works! I think that IMESupport are incompatible with the IME default installed in win10, so you can try other input method

**Comment by tennc** [comment]
@renzongxian Google pinyin input method  IMESupport not run

**Comment by kngxscn** [comment]
@tennc It really works on my computer. Sublime text 3 Build 3083, windows 10
![](http://ww2.sinaimg.cn/mw690/8c7400efgw1ez55pt05haj20mn0hvmxi.jpg)

**Comment by tennc** [comment]
@renzongxian   sublime text3 dev  3095   win10 x64 11082 not work

**Comment by Potat0000** [comment]
When I use QQ pinyin input method, IMESupport works. But I like win10 default IME. When can you fix this?

**Comment by tennc** [comment]
@gyj1109 @renzongxian  qq pinyin  ~ ok~~

**Comment by YuFong** [comment]
win10 10586  64bit ,sublime text 3 doesn't work with default input method

**Comment by tennc** [comment]
@YuFong  qqpinyin  ok

**Comment by zhanba** [comment]
win10 and google pinyin worked

**Comment by YONGTAN** [comment]
sougou pinyin doesn't work

**Comment by warmilk** [comment]
Me2 ! 
No use for Windows10 ! 
I use the default microsoft keyboard to input Chinese，But it doesn't work……

**Comment by warmilk** [comment]
Me2 ! 
No use for Windows10 ! 
I use the default microsoft keyboard to input Chinese，But it doesn't work……

**Comment by warmilk** [comment]
Me2 ! 
No use for Windows10 ! 
I use the default microsoft keyboard to input Chinese，But it doesn't work……

**Comment by warmilk** [comment]
Me2 ! 
No use for Windows10 ! 
I use the default microsoft keyboard to input Chinese，But it doesn't work……

**Comment by warmilk** [comment]
Me2 ! 
No use for Windows10 ! 
I use the default microsoft keyboard to input Chinese，But it doesn't work……

**Comment by warmilk** [comment]
Me2 ! 
No use for Windows10 ! 
I use the default microsoft keyboard to input Chinese，But it doesn't work……

**Comment by warmilk** [comment]
Me2 ! 
No use for Windows10 ! 
I use the default microsoft keyboard to input Chinese，But it doesn't work……

**Comment by warmilk** [comment]
Me2 ! 
No use for Windows10 ! 
I use the default microsoft keyboard to input Chinese，But it doesn't work……

**Comment by warmilk** [comment]
Me2 ! 
No use for Windows10 ! 
I use the default microsoft keyboard to input Chinese，But it doesn't work……

**Comment by tennc** [comment]
@warmilk qq pinyin work

**Comment by warmilk** [comment]
@tennc THX !
